apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-first-app
          image: 534626096554.dkr.ecr.us-east-1.amazonaws.com/webapp
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
      - name: ecr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
